### ISSUE TITLE
Detailed HVAC Viewer TODO

### ISSUE THREAD

**Issue by mdahlhausen** [BuildingPerformanceSimulation/openstudio-measures#32]
A to do list for the Detailed HVAC Viewer measure:

Data schema / measure:
- [ ] figure out connectors and splitters
- [ ] figure out zone objects on zone side
- [ ] add option to output data for only a specific loop, not all loops
- [ ] add informational content for non-node objects

Viewer:
- [ ] get the dropdown loop selection to work; it isn't regenerating the network graph
- [ ] add demand side (may require more in the data for the demand side, particularly zone)
- [ ] add connectors / splitters (requires work on schema)
- [ ] add the ability to filter x and y axis, set min/max time or range
- [ ] use a fixed color-blind safe color scheme
- [ ] general style improvements
- [ ] psychrometric chart plot?

Overall:
- [ ] Add more tests
